services:
  tmodloader:
    image: ghcr.io/f3rym/terraria-server:latest
    container_name: tmodloader
    restart: unless-stopped

    ports:
      - "7777:7777"

    volumes:
      - ./Worlds:/root/.local/share/Terraria/tModLoader/Worlds
